name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master

env:
  NODE_ENV: test
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
  REDIS_URL: redis://redis:6379

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432
      redis:
        image: redis:latest
        ports:
          - 6379

    steps:
      # Step 1 - Checkout code
      - uses: actions/checkout@v3

      # Step 2 - Setting up Node.js environment
      - uses: ./.github/workflows/shared

      # Step 3 - Running prettier check
      - name: Run Prettier Check
        run: npm run prettier

      # Step 4 - Running linter
      - name: Run Linter
        run: npm run lint

      # Step 5 - View Redis logs (optional for debugging)
      - name: View Redis Logs (optional)
        run: |
          docker ps -a # list all containers to check their status
          docker logs redis # view logs from the Redis container

      # Step 6 - Running tests
      - name: Run Tests
        run: npm test

      # Step 7 - Running build (only if everything else succeeds)
      - name: Run Build
        run: npm run build
